# NjMgNjAgNDAgNjMgNjEgNDAgNjMgNjEgNDAgNjMgNjEgNDAgNjMgNjAgNDAgNjMgNjAgNDAgNjMgNjAgNDAgNjMgNjEgNDAgNjIgNjAgNDAgNjMgNjAgNDAgNjMgNjEgNDAgNjMgNjEgNDAgNjMgNjEgNDAgNjMgNjAgNDAgNjMgNjEgNDAgNjMgNjAgNDAgNjMgNjEgNDAgNjIgNjAgNDAgNjMgNjAgNDAgNjMgNjEgNDAgNjMgNjEgNDAgNjMgNjAgNDAgNjMgNjAgNDAgNjMgNjAgNDAgNjMgNjAgNDAgNjMgNjEgNDAgNjIgNjAgNDAgNjMgNjAgNDAgNjMgNjEgNDAgNjMgNjEgNDAgNjMgNjAgNDAgNjMgNjAgNDAgNjMgNjEgNDAgNjMgNjAgNDAgNjMgNjAgNDAgNjIgNjAgNDAgNjMgNjAgNDAgNjMgNjEgNDAgNjMgNjEgNDAgNjMgNjEgNDAgNjMgNjAgNDAgNjMgNjAgNDAgNjMgNjEgNDAgNjMgNjAgNDAgNjIgNjAgNDAgNjMgNjAgNDAgNjMgNjEgNDAgNjMgNjEgNDAgNjMgNjEgNDAgNjMgNjAgNDAgNjMgNjEgNDAgNjMgNjAgNDAgNjMgNjEgNDAgNjIgNjAgNDAgNjMgNjAgNDAgNjMgNjEgNDAgNjMgNjEgNDAgNjMgNjEgNDAgNjMgNjAgNDAgNjMgNjAgNDAgNjMgNjAgNDAgNjMgNjAgNDAgNjIgNjAgNDAgNjMgNjAgNDAgNjMgNjEgNDAgNjMgNjEgNDAgNjMgNjAgNDAgNjMgNjEgNDAgNjMgNjEgNDAgNjMgNjAgNDAgNjMgNjAgNDAgNjIgNjAgNDAgNjMgNjAgNDAgNjMgNjEgNDAgNjMgNjEgNDAgNjMgNjAgNDAgNjMgNjAgNDAgNjMgNjEgNDAgNjMgNjAgNDAgNjMgNjEgNDAgNjIgNjAgNDAgNjMgNjAgNDAgNjMgNjAgNDAgNjMgNjEgNDAgNjMgNjAgNDAgNjMgNjAgNDAgNjMgNjAgNDAgNjMgNjAgNDAgNjMgNjAgNDAgNjIgNjAgNDAgNjMgNjAgNDAgNjMgNjEgNDAgNjMgNjEgNDAgNjMgNjAgNDAgNjMgNjAgNDAgNjMgNjEgNDAgNjMgNjAgNDAgNjMgNjEgNDAgNjIgNjAgNDAgNjMgNjAgNDAgNjMgNjEgNDAgNjMgNjEgNDAgNjMgNjAgNDAgNjMgNjEgNDAgNjMgNjEgNDAgNjMgNjEgNDAgNjMgNjAgNDAgNjIgNjAgNDAgNjMgNjAgNDAgNjMgNjEgNDAgNjMgNjEgNDAgNjMgNjAgNDAgNjMgNjAgNDAgNjMgNjAgNDAgNjMgNjEgNDAgNjMgNjEgNDAgNjIgNjAgNDAgNjMgNjAgNDAgNjMgNjEgNDAgNjMgNjEgNDAgNjMgNjAgNDAgNjMgNjEgNDAgNjMgNjEgNDAgNjMgNjEgNDAgNjMgNjEgNDAgNjIgNjAgNDAgNjMgNjAgNDAgNjMgNjEgNDAgNjMgNjEgNDAgNjMgNjAgNDAgNjMgNjAgNDAgNjMgNjEgNDAgNjMgNjAgNDAgNjMgNjAgNDAgNjIgNjAgNDAgNjMgNjAgNDAgNjMgNjEgNDAgNjMgNjEgNDAgNjMgNjAgNDAgNjMgNjAgNDAgNjMgNjEgNDAgNjMgNjAgNDAgNjMgNjEgNDAgNjIgNjAgNDAgNjMgNjAgNDAgNjMgNjEgNDAgNjMgNjEgNDAgNjMgNjAgNDAgNjMgNjAgNDAgNjMgNjEgNDAgNjMgNjAgNDAgNjMgNjA=

# Try using cyberchef to decode this! https://gchq.github.io/CyberChef/

import base64

number = 1043

print("Binary", bin(number))
print("Hexadecimal", hex(number))
print("Octal", oct(number))

base64String = base64.b64encode("hello!".encode())
print(base64String)

# On cyberchef, try turning files into base64! Then, try converting base64 into an image https://codebeautify.org/base64-to-image-converter



